# Generated by Django 4.2.11 on 2024-09-11 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeUploadBlofin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('underlying_asset', models.CharField(max_length=10)),
                ('margin_mode', models.CharField(max_length=10)),
                ('leverage', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('side', models.CharField(max_length=4)),
                ('avg_fill', models.DecimalField(decimal_places=20, max_digits=40)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('original_filled_quantity', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=20)),
                ('reduce_only', models.BooleanField()),
                ('trade_status', models.CharField(max_length=10)),
                ('exchange', models.CharField(choices=[('BloFin', 'BloFin'), ('OtherExchange', 'Other Exchange')], default='', max_length=100)),
                ('is_open', models.BooleanField(default=None)),
                ('is_matched', models.BooleanField(default=None)),
                ('is_partially_matched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blofin_futures_csv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_time'],
                'unique_together': {('underlying_asset', 'avg_fill', 'fee')},
            },
        ),
    ]
