# Generated by Django 4.2.11 on 2024-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='file_name',
            field=models.CharField(max_length=35),
        ),
    ]
