# Generated by Django 4.2.11 on 2024-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_alter_tradeuploadblofin_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='file_name',
            field=models.CharField(max_length=250),
        ),
    ]
