# Generated by Django 4.2.11 on 2024-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0006_filename_cancel_processing_filename_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
